import React from 'react';
import type { LucideIcon } from 'lucide-react';
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Calendar,
  Check,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clipboard,
  Clock,
  Code,
  Copy,
  Cpu,
  Database,
  Download,
  DownloadCloud,
  Edit,
  Edit2,
  Edit3,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileText,
  Filter,
  Folder,
  FolderOpen,
  Globe,
  HelpCircle,
  History,
  Info,
  Key,
  Layers,
  Link,
  List,
  Loader2,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Maximize2,
  Minimize2,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Pause,
  Pencil,
  Play,
  Plus,
  PlusCircle,
  Power,
  Redo,
  RefreshCcw,
  RefreshCw,
  RotateCcw,
  RotateCw,
  Save,
  Search,
  Send,
  Server,
  Settings,
  Share2,
  Sliders,
  Sparkles,
  StopCircle,
  Sun,
  Terminal,
  Trash,
  Trash2,
  Undo,
  Unlock,
  Upload,
  UploadCloud,
  User,
  Users,
  X,
  XCircle,
  Zap,
} from 'lucide-react';

// Static registry of common icons (normalized to kebab-case)
const staticIconRegistry: Record<string, LucideIcon> = {
  'activity': Activity,
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'calendar': Calendar,
  'check': Check,
  'check-circle': CheckCircle,
  'check-circle-2': CheckCircle2,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'clipboard': Clipboard,
  'clock': Clock,
  'code': Code,
  'copy': Copy,
  'cpu': Cpu,
  'database': Database,
  'download': Download,
  'download-cloud': DownloadCloud,
  'edit': Edit,
  'edit-2': Edit2,
  'edit-3': Edit3,
  'external-link': ExternalLink,
  'eye': Eye,
  'eye-off': EyeOff,
  'file': File,
  'file-text': FileText,
  'filter': Filter,
  'folder': Folder,
  'folder-open': FolderOpen,
  'globe': Globe,
  'help-circle': HelpCircle,
  'history': History,
  'info': Info,
  'key': Key,
  'layers': Layers,
  'link': Link,
  'list': List,
  'loader-2': Loader2,
  'lock': Lock,
  'login': LogIn,
  'log-in': LogIn,
  'logout': LogOut,
  'log-out': LogOut,
  'mail': Mail,
  'maximize': Maximize2,
  'maximize-2': Maximize2,
  'minimize': Minimize2,
  'minimize-2': Minimize2,
  'moon': Moon,
  'more-horizontal': MoreHorizontal,
  'more-vertical': MoreVertical,
  'pause': Pause,
  'pencil': Pencil,
  'play': Play,
  'plus': Plus,
  'plus-circle': PlusCircle,
  'power': Power,
  'redo': Redo,
  'refresh': RefreshCw,
  'refresh-cw': RefreshCw,
  'refresh-ccw': RefreshCcw,
  'rotate-ccw': RotateCcw,
  'rotate-cw': RotateCw,
  'save': Save,
  'search': Search,
  'send': Send,
  'server': Server,
  'settings': Settings,
  'share': Share2,
  'share-2': Share2,
  'sliders': Sliders,
  'sparkles': Sparkles,
  'stop': StopCircle,
  'stop-circle': StopCircle,
  'sun': Sun,
  'terminal': Terminal,
  'trash': Trash,
  'trash-2': Trash2,
  'undo': Undo,
  'unlock': Unlock,
  'upload': Upload,
  'upload-cloud': UploadCloud,
  'user': User,
  'users': Users,
  'x': X,
  'x-circle': XCircle,
  'zap': Zap,
};

export function normalizeIconName(iconName: string | undefined): string | null {
  if (!iconName) return null;
  return iconName
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/_/g, '-')
    .toLowerCase()
    .trim();
}

/**
 * Get an action icon component by name. Returns registered Lucide icons directly.
 */
export function getActionIconComponent(
  iconName: string | undefined
): React.ComponentType<{ className?: string }> | null {
  const normalized = normalizeIconName(iconName);
  if (!normalized) return null;

  return staticIconRegistry[normalized] || null;
}
