"""
Example: File Upload and Download in pydantic-ui

This example demonstrates how to:
- Use the FileUpload renderer to upload files
- Handle file data in the backend
- Trigger file downloads from the backend using callbacks
"""

import base64
import sys
from typing import Annotated

import uvicorn
from fastapi import FastAPI
from pydantic import BaseModel, Field

sys.path.insert(0, str(__file__).replace("\\", "/").rsplit("/", 3)[0])

from pydantic_ui import (
    ActionButton,
    FieldConfig,
    PydanticUIController,
    Renderer,
    UIConfig,
    create_pydantic_ui,
)


# Define a model to match the frontend's file data structure
class FileData(BaseModel):
    name: str
    size: int
    type: str
    data: str | None = None  # Base64 encoded data URL


class FileTransferModel(BaseModel):
    """File Transfer Demo"""

    # File upload field
    uploaded_file: Annotated[
        FileData | None,
        FieldConfig(
            renderer=Renderer.FILE_UPLOAD,
            label="Upload a file",
            props={
                "accept": ".txt,.md,.json,.png,.jpg",
                "maxSize": 5 * 1024 * 1024,  # 5MB
            },
        ),
    ] = None

    notes: str = Field(default="", description="Notes about the file")


app = FastAPI(title="Pydantic UI File Transfer Example")

ui_config = UIConfig(
    title="File Transfer Demo",
    description="Upload files and download generated content.",
    actions=[
        ActionButton(
            id="download_sample",
            label="Download Sample",
            icon="download",
            variant="secondary",
        ),
        ActionButton(
            id="echo_file",
            label="Echo Uploaded File",
            icon="refresh-cw",
            variant="default",
            tooltip="Download the currently uploaded file",
        ),
        ActionButton(
            id="process_upload",
            label="Upload & Process",
            icon="upload",
            variant="default",
            upload_file=True,
            tooltip="Upload a file and process it immediately",
        ),
    ],
)

router = create_pydantic_ui(
    FileTransferModel,
    ui_config=ui_config,
)


@router.action("process_upload")
async def process_upload(data: dict, controller: PydanticUIController):
    """Handle file upload directly from action button."""
    if not controller.uploaded_file:
        await controller.show_toast("No file received!", "error")
        return

    file_info = controller.uploaded_file
    name = file_info["name"]
    size = file_info["size"]
    
    # Update the notes field with file info
    new_notes = f"Processed file: {name} ({size} bytes)\nTimestamp: {12345}"
    
    # Update the model data
    current_data = data.copy()
    current_data["notes"] = new_notes
    
    await controller.push_data(current_data)
    await controller.show_toast(f"Processed {name}", "success")


@router.action("download_sample")
async def download_sample(data: dict, controller: PydanticUIController):
    """Generate a sample text file and trigger download."""
    content = "Hello! This is a sample file generated by the backend.\nTimestamp: 1234567890"
    # Encode content to base64
    b64_content = base64.b64encode(content.encode("utf-8")).decode("utf-8")
    # Create data URL
    data_url = f"data:text/plain;base64,{b64_content}"
    
    await controller.show_toast("Downloading sample file...", "info")
    await controller.download_file("sample_generated.txt", data_url)


@router.action("echo_file")
async def echo_file(data: dict, controller: PydanticUIController):
    """Read the uploaded file from data and send it back as a download."""
    model = FileTransferModel.model_validate(data)
    
    if not model.uploaded_file:
        await controller.show_toast("No file uploaded!", "error")
        return

    file_data = model.uploaded_file
    
    # In a real app, you might process the file here
    # For this demo, we just send it back with a prefix in the name
    
    new_filename = f"echo_{file_data.name}"
    
    await controller.show_toast(f"Downloading {new_filename}...", "success")
    
    # file_data.data is already a data URL (e.g. "data:text/plain;base64,...")
    if file_data.data:
        await controller.download_file(new_filename, file_data.data)
    else:
        await controller.show_toast("File has no data content", "error")


app.include_router(router)

if __name__ == "__main__":
    print("Starting File Transfer Demo...")
    print("Open http://localhost:8000 in your browser")
    uvicorn.run(app, host="0.0.0.0", port=8000)
